# spring.application.name=eureka-server
# server.port=8761

# # Eureka server DOES NOT register itself
# eureka.client.register-with-eureka=false
# eureka.client.fetch-registry=false

# # Server URL (used internally)
# eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# # Development friendly
# eureka.server.enable-self-preservation=false

# # Actuator
# management.endpoints.web.exposure.include=*


spring.application.name=eureka-server
server.port=8761

eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


